# These are supported funding model platforms
github: talonsmart
patreon: talonsmart
open_collective: talonsmart
ko_fi: talonsmart
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: talonsmart
issuehunt: talonsmart
otechie: # Replace with a single Otechie username
custom: # Replace with a single custom sponsorship URL
